# Permalink style
permalink: pretty

# Basic website configuration
url: /
assets: /assets/
markdown: kramdown

# Set the site defaults
title: JS Medical

# Set the frontmatter defaults
defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: "default"

# Pagination
paginate: 5
paginate_path: "/news/page/:num/"

excerpt_separator: <!--more-->

# Exclusions
exclude: ["README.md", "CNAME", ".gitignore", ".gitlab-ci.yml"]

# Plugins
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-git_metadata